name: Build

on:
  push:

env:
  outDir: target/dx/web/release/web/public

jobs:
  build:
    name: dx build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main

      - run: cargo binstall dioxus-cli --force

      - name: Build Project 🎁
        run: dx bundle --package web --release

      - uses: actions/upload-artifact@v4
        if: "${{ github.ref == 'refs/heads/main' }}"
        with:
          name: artifact
          path: ${{ env.outDir }}
          compression-level: 9 # maximum compression
          if-no-files-found: error
          retention-days: 2

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3 # Needed for final step
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ${{ env.outDir }}

      - name: Add CNAME
        if: "${{ env.cname != '' }}"
        run: cd ${{ env.outDir }} && echo "${{ env.cname }}" > CNAME

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.outDir }}
          clean: false
